window.prompts =
[ // u9f1 u9f1 speculating
	{text:"You are scheduling a meeting. Talk about its duration. Use the table to help you.",
	audio: "g1",
	image: "1.png"},
	{text:"You are planning a workshop. Talk about its duration. Use the table to help you.",
	audio: "g2",
	image: "2.png"},
	{text:"You repaired a pump. Talk about the duration of the repair work. Use the table to help you.",
	audio: "g3",
	image: "3.png"},
	{text:"Your co-worker Ahmed wants you to attend a meeting. Ask Ahmed about its duration.",
	audio: "g4",
	image: ""},
	{text:"Your co-worker Noora's shift is about to start. Ask Noora about its duration.",
	audio: "g5",
	image: ""},
	{text:"Your co-worker Kamal started working at the company in 2020. Talk about duration.",
	audio: "g6",
	image: ""},
	{text:"You have a leadership course coming up. Talk about its duration. Use the table to help you.",
	audio: "g7",
	image: "7.png"},
	{text:"You are organizing a safety inspection. Talk about its duration. Use the table to help you.",
	audio: "g8",
	image: "8.png"},
	{text:"You have just completed some maintenance work. Talk about its duration. Use the table to help you.",
	audio: "g9",
	image: "9.png"},
	{text:"Your co-worker Sara took a break. Talk about its duration. Use the table to help you.",
	audio: "g10",
	image: "10.png"},
	
]
